import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import {Toaster} from "react-hot-toast";
const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Blogo Blog App",
  description: "Generated by Mohamed Saleh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />

          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
